This is c:\developuni\miktex\miktex\bin\makeindex.exe, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/developuni/ies_project/report/IesProject.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file IesProject.acn....done (132 entries accepted, 0 rejected).
Sorting entries....done (1126 comparisons).
Generating output file IesProject.acr....done (97 lines written, 0 warnings).
Output written in IesProject.acr.
Transcript written in IesProject.alg.
