This is c:\Program Files (x86)\MiKTeX 2.9\miktex\bin\makeindex.exe, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file H:/studium/ies-project/report/IesProject.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file IesProject.acn....done (122 entries accepted, 0 rejected).
Sorting entries....done (945 comparisons).
Generating output file IesProject.acr....done (92 lines written, 0 warnings).
Output written in IesProject.acr.
Transcript written in IesProject.alg.
