/*
 * (C) Copyright 2007-2008 Michal Simek
 *
 * Michal SIMEK <monstr@monstr.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 *
 * CAUTION: This file is automatically generated by libgen.
 * Version: Xilinx EDK 14.1 EDK_P.15xf
 * Generate by U-BOOT v4.00.c
 * Project description at http://www.monstr.eu/uboot/
 */

#define XILINX_BOARD_NAME	"test"

/* Microblaze is microblaze_0 */
#define XILINX_USE_MSR_INSTR	1
#define XILINX_PVR		0
#define XILINX_FSL_NUMBER	0
#define XILINX_USE_ICACHE	1
#define XILINX_USE_DCACHE	1
#define XILINX_DCACHE_BYTE_SIZE	4096

/* Interrupt controller is xps_intc_0 */
#define XILINX_INTC_BASEADDR		0x81800000
#define XILINX_INTC_NUM_INTR_INPUTS	10

/* Timer pheriphery is xps_timer_0 */
#define XILINX_TIMER_BASEADDR	0x83c00000
#define XILINX_TIMER_IRQ	6

/* System Timer Clock Frequency */
#define XILINX_CLOCK_FREQ	125000000

/* Uart console is RS232_Uart_1 */
#define XILINX_UART16550
#define XILINX_UART16550_BASEADDR	0x83e20000
#define XILINX_UART16550_CLOCK_HZ	125000000
#define CONFIG_SYS_NS16550_COM2		0x83e01000
#define XILINX_UARTLITE_BASEADDR	0x84400000
#define CONFIG_CONS_INDEX		2

/* IIC pheriphery is IIC_EEPROM */
#define XILINX_IIC_0_BASEADDR	0x81600000
#define XILINX_IIC_0_FREQ	100000
#define XILINX_IIC_0_BIT	0

/* GPIO is LEDs_8Bit*/
#define XILINX_GPIO_BASEADDR	0x81440000

/* Main Memory is DDR2_SDRAM */
#define XILINX_RAM_START	0x90000000
#define XILINX_RAM_SIZE		0x10000000

/* Flash Memory is SRAM_FLASH */
#define XILINX_FLASH_START	0x8c000000
#define XILINX_FLASH_SIZE	0x02000000

/* Sysace Controller is SysACE_CompactFlash */
#define XILINX_SYSACE_BASEADDR	0x83600000
#define XILINX_SYSACE_MEM_WIDTH	16

/* Ethernet controller is Hard_Ethernet_MAC */
#define XILINX_LLTEMAC_BASEADDR			0x82000000
#define XILINX_LLTEMAC_SDMA_CTRL_BASEADDR	0x84600080
